### PR TITLE
Code refactor, fix in projects and branch list added

### PR DESCRIPTION
**Pull request by tiagobcx**

### CODE REVIEW

**Comment by pedrompflopes** [comment]
Logo
**Checkmarx AST \- Scan Summary & Details** - [17cdfee8\-f990\-4fe1\-b4a1\-9501de46cf42](https://ast-master.dev.cxast.net/projects/2f2e245d-226a-4810-84cd-e38eb48d63e9/scans?id=17cdfee8-f990-4fe1-b4a1-9501de46cf42&branch=feature/AST-6782_branches)
### No Violations Found

**Review by jay-nanduri — COMMENTED** [review]
looks like the test cases are failing in ci/cd. Can you check once?

**Comment by tiagobcx** [comment]
> looks like the test cases are failing in ci/cd. Can you check once?

fixed

**Review by jay-nanduri — COMMENTED** [review]
changes look fine

**Review by pedrompflopes — APPROVED** [review]

**Pull request merged**
